blank_issues_enabled: false
contact_links:
  - name: Ask a question or seek support
    url: https://github.com/m-samland/trap/discussions
    about: Use Discussions for questions, support, or other topics.