name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  lint:
    name: 🧹 Lint with Ruff
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Ruff
        run: |
          python -m pip install --upgrade pip
          pip install ruff

      - name: Run Ruff check
        run: |
          ruff check .

  test:
    name: 🧪 Test with pytest (Python ${{ matrix.python-version }})
    runs-on: ubuntu-latest
    needs: lint  # Ensures linting passes before running tests

    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ".[test]"

      - name: Run pytest
        run: |
          pytest tests
